VLOG_LIST := \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/ipsim/blk_mem_1024_29_sim_netlist.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/ipsim/blk_mem_16k_23_sim_netlist.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/ipsim/fifo_1k_5bit_sim_netlist.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/ipsim/fifo_1k_9bit_sim_netlist.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/ipsim/fifo_8k_14bit_sim_netlist.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/lzw_backward_byte_reverse.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/lzw_backward_data_recover.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/lzw_backward_decompress.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/lzw_backward_dictionary.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/lzw_backward_dictionary_consult.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/lzw_forward_compress.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/lzw_forward_dictionary.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/lzw_forward_framer.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/lzw_forward_prepare.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/rtl/sync_reset.v \
/media/cqiu/Document/work/prj/AIPrj/sim/sim_fxx/tb/btc/qst_vrd_nuvm_vvd1602_nhls_tc1_lzw/tb_lzw_top.v \
